### ISSUE TITLE
format for windmill.yml

### ISSUE THREAD

**Issue by sbbagal13** [mayansalama/windmill#25]
Hi All, 
Do we have template to update values from windmill.yml
I would like to run the project in Docker container and wants to change hostname from 127.0.0.1 to 0.0.0.0 to get accessible outside container.

**Comment by sbbagal13** [comment]
I found the solution. Closing issue. If anyone faced same let me know , I am happy to provide you solution

**Comment by TomKlimovski** [comment]
thanks @sbbagal13 !
